version: '3.8'
services:
  rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

  sentiments_app:
        image: sentiments_app:sentiments_app
        container_name: sentiments_app
        restart: always
        depends_on:
              - rabbitmq
              - worker1
              - worker2
        expose:
            - 5000
  worker1:
        image: worker_app:worker_app
        container_name: worker1_app
        restart: always
        depends_on:
              - rabbitmq

  worker2:
        image: worker_app:worker_app
        container_name: worker2_app
        restart: always
        depends_on:
              - rabbitmq

  sentiments_web:
       image: sentiments_web:sentiments_web
       container_name: sentiments_web
       restart: always
       ports:
          - 80:80
       depends_on:
          - sentiments_app