version: '3.8'
services:
  rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

  flask:
        image: sunnfunn1970/sentiment:flask
        command: python3 sentiment.py
        restart: always
        ports:
            - 80:5000
        depends_on:
              - rabbitmq
              - model
  model:
        image: sunnfunn1970/sentiment:model
        command: python3 worker.py
        restart: always
        depends_on:
              - rabbitmq