cookie:
  expiry_days: 0
  key: ajkla
  name: heart_cookies
credentials:
  usernames:
    grisha:
      email: grisha199506@mail.ru
      name: Alexey Tretyakov
      password: $2b$12$jOA8.IrX6hVjyIC4ZVTa5uqlPqwyj9fMSd1olxvVe9aYDBvmlpcoa
preauthorized:
  emails:
  - grisha199506@mail.ru